DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS data;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEST NOT NULL
);

CREATE TABLE data (
    time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
    img1 INT NOT NULL,
    img2 INT NOT NULL,
    img3 INT NOT NULL,
    img4 INT NOT NULL,
    img5 INT NOT NULL,
    average INT NOT NULL
);